server1: server1.c client.c
	gcc -Wall -o ../bin/server server1.c
	gcc -Wall -o ../bin/client client.c


server2: server2.c client.c
	gcc -Wall -o ../bin/server server2.c
	gcc -Wall -o ../bin/client client.c

clean:
	rm ../bin/*